// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP normr_logical2Int(SEXP idxSEXP);
SEXP normr_logical2Count(SEXP vecSEXP, SEXP nthreadsSEXP);
SEXP normr_logRowSum(SEXP matSEXP, SEXP nthreadsSEXP);
SEXP normr_logSumVector(SEXP vecSEXP, SEXP nthreadsSEXP);
SEXP normr_sumVector(SEXP vecSEXP, SEXP nthreadsSEXP);
SEXP normr_mapToUniquePairs(SEXP rSEXP, SEXP sSEXP);
SEXP normr_mapToOriginal(SEXP vecSEXP, SEXP mapSEXP);
SEXP normr_getEnrichment(SEXP posteriorsSEXP, SEXP rSEXP, SEXP sSEXP, SEXP kSEXP);
SEXP normr_diffr_core(SEXP rSEXP, SEXP sSEXP, SEXP modelsSEXP, SEXP epsSEXP, SEXP verboseSEXP, SEXP nthreadsSEXP);

R_CallMethodDef callMethods[]  = {
  {"normr_logical2Int", (DL_FUNC) &normr_logical2Int, 1},
  {"normr_logical2Count", (DL_FUNC) &normr_logical2Count, 2},
  {"normr_logRowSum", (DL_FUNC) &normr_logRowSum, 2},
  {"normr_logSumVector", (DL_FUNC) &normr_logSumVector, 2},
  {"normr_sumVector", (DL_FUNC) &normr_sumVector, 2},
  {"normr_mapToUniquePairs", (DL_FUNC) &normr_mapToUniquePairs, 2},
  {"normr_mapToOriginal", (DL_FUNC) &normr_mapToOriginal, 2},
  {"normr_getEnrichment", (DL_FUNC) &normr_getEnrichment, 4},
  {"normr_diffr_core", (DL_FUNC) &normr_diffr_core, 6},
  {NULL, NULL, 0}
};

void R_init_normr(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

