// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// em
List em(const NumericVector& r, const NumericVector& s, int models = 2, double eps = .001, bool verbose = true);
RcppExport SEXP diffr_em(SEXP rSEXP, SEXP sSEXP, SEXP modelsSEXP, SEXP epsSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< const NumericVector& >::type r(rSEXP );
        Rcpp::traits::input_parameter< const NumericVector& >::type s(sSEXP );
        Rcpp::traits::input_parameter< int >::type models(modelsSEXP );
        Rcpp::traits::input_parameter< double >::type eps(epsSEXP );
        Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP );
        List __result = em(r, s, models, eps, verbose);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
