# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logRowSum <- function(mat, nthreads = 1L) {
    .Call('normr_logRowSum', PACKAGE = 'normr', mat, nthreads)
}

logSumVector <- function(vec, nthreads = 1L) {
    .Call('normr_logSumVector', PACKAGE = 'normr', vec, nthreads)
}

mapToOriginal <- function(vec, m2u) {
    .Call('normr_mapToOriginal', PACKAGE = 'normr', vec, m2u)
}

mapToUniqueWithMap <- function(vec, m2u) {
    .Call('normr_mapToUniqueWithMap', PACKAGE = 'normr', vec, m2u)
}

computeEnrichmentWithMap <- function(lnPost, m2u, theta, F = 1L, B = 0L, diffCall = FALSE, nthreads = 1L) {
    .Call('normr_computeEnrichmentWithMap', PACKAGE = 'normr', lnPost, m2u, theta, F, B, diffCall, nthreads)
}

computeEnrichment <- function(r, s, lnPost, theta, F = 1L, B = 0L, diffCall = FALSE, nthreads = 1L) {
    .Call('normr_computeEnrichment', PACKAGE = 'normr', r, s, lnPost, theta, F, B, diffCall, nthreads)
}

normr_core <- function(r, s, models = 2L, eps = 1e-5, iterations = 5L, bgIdx = 0L, diffCall = FALSE, verbose = FALSE, nthreads = 1L) {
    .Call('normr_normr_core', PACKAGE = 'normr', r, s, models, eps, iterations, bgIdx, diffCall, verbose, nthreads)
}

