# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

em <- function(r, s, models = 2L, eps = .001, verbose = TRUE) {
    .Call('diffr_em', PACKAGE = 'diffr', r, s, models, eps, verbose)
}

